spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:PORT/DB-NAME
    username: USERNAME
    password: PASSWORD
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  redis:
    host: redis
    port: 6379
  cache:
    type: redis

jwt:
  secret: "YOUR_SUPER_SECRET_KEY"